#if !defined(NUI_WIDGET_TYPE_H) && !defined(NUI_WIDGET_TYPE_BEGIN)
#define NUI_WIDGET_TYPE_H
#define NUI_WIDGET_TYPE_FIRST
#endif

#if defined(NUI_WIDGET_TYPE_FIRST) || defined(NUI_WIDGET_TYPE_BEGIN)

#ifndef NUI_WIDGET_TYPE_BEGIN
#define NUI_WIDGET_TYPE_BEGIN enum nui_widget_type {
#define NUI_WIDGET_TYPE_ENTRY(NAME, STRNAME) NUI_WIDGET_TYPE_##NAME,
#define NUI_WIDGET_TYPE_END };
#endif

NUI_WIDGET_TYPE_BEGIN
NUI_WIDGET_TYPE_ENTRY(WINDOW, "window")
NUI_WIDGET_TYPE_ENTRY(BUTTON, "button")
NUI_WIDGET_TYPE_END

#undef NUI_WIDGET_TYPE_FIRST
#undef NUI_WIDGET_TYPE_BEGIN
#undef NUI_WIDGET_TYPE_END
#undef NUI_WIDGET_TYPE_ENTRY

#endif
